"""Demo mode: synthetic postings and an offline HTTP transport.

Everything here is fictional. Company names are invented, descriptions are composed from
templates, and the same seed always produces the same data, so screenshots and tests agree.
"""

from __future__ import annotations

import json
import random
from datetime import UTC, datetime, timedelta
from pathlib import Path

import httpx

from .models import Job

COMPANIES: list[tuple[str, str, str]] = [
    ("Nordlicht Analytics GmbH", "Berlin, Germany", "DE"),
    ("Quorum Compliance GmbH", "Munich, Germany", "DE"),
    ("Rheinwerk Data AG", "Cologne, Germany", "DE"),
    ("Tulip Data B.V.", "Amsterdam, Netherlands", "NL"),
    ("Liffey Systems Ltd", "Dublin, Ireland", "IE"),
    ("Tejo Labs Lda", "Lisbon, Portugal", "PT"),
    ("Fjord ML AB", "Stockholm, Sweden", "SE"),
    ("Øresund Insights ApS", "Copenhagen, Denmark", "DK"),
    ("Alpenstein AG", "Zurich, Switzerland", "CH"),
    ("Donau Digital GmbH", "Vienna, Austria", "AT"),
    ("Ibéria Cloud S.L.", "Madrid, Spain", "ES"),
    ("Seine Intelligence SAS", "Paris, France", "FR"),
    ("Helix Legal AI", "Remote, Europe", "EU"),
    ("Baltic Graph OÜ", "Tallinn, Estonia", None),
]
ROLES = [
    "AI Engineer",
    "Data Engineer",
    "LLM Engineer",
    "Machine Learning Engineer",
    "Analytics Engineer",
    "Backend Engineer (Python)",
    "Data Platform Engineer",
    "Applied AI Engineer",
    "Data Scientist",
    "Solutions Engineer",
]
SENIORITY = [("Junior ", 0.20), ("", 0.45), ("Senior ", 0.28), ("Staff ", 0.07)]
SKILL_LINES = [
    "Python and SQL every day; PostgreSQL in production.",
    "Building LLM features with the Claude API or comparable models, with structured outputs and evals.",
    "Designing ETL/ELT pipelines with dbt or Airflow and a warehouse (BigQuery, Snowflake or DuckDB).",
    "Retrieval-augmented generation over document corpora with citations and hallucination checks.",
    "TypeScript and Next.js for internal tools.",
    "Docker, GitHub Actions and one major cloud (AWS or Azure).",
    "Batch processing of large document sets with idempotent, restartable jobs.",
    "Pydantic or Zod schemas at every model boundary.",
    "Observability for LLM calls: cost, latency and quality dashboards.",
    "Kubernetes and Terraform for platform work.",
    "Spark or Flink for streaming workloads.",
    "Java or Scala in a JVM-heavy stack.",
]
LANGUAGE_LINES = [
    ("Fluent German (C1) is required for daily work with public-sector clients.", 0.30),
    ("German is a plus but not required; our working language is English.", 0.20),
    ("English-speaking team; no German needed.", 0.50),
]
VISA_LINES = [
    ("We offer visa sponsorship and a relocation package for candidates moving to Europe.", 0.35),
    (
        "Applicants must already hold a valid EU work permit; we cannot sponsor visas for this role.",
        0.15,
    ),
    ("", 0.50),
]
WORKPLACE_LINES = [
    ("Hybrid: three days a week in the office.", 0.45),
    ("Fully remote within the EU.", 0.30),
    ("On-site role.", 0.25),
]
SOURCES = ["arbeitnow", "greenhouse", "lever", "bundesagentur"]


def _pick(rng: random.Random, options: list[tuple[str, float]]) -> str:
    return rng.choices([o for o, _ in options], weights=[w for _, w in options], k=1)[0]


def generate_jobs(
    count: int = 120, seed: int = 20260101, today: datetime | None = None
) -> list[Job]:
    rng = random.Random(seed)
    today = today or datetime(2026, 9, 24, tzinfo=UTC)
    jobs: list[Job] = []
    for n in range(1, count + 1):
        company, location, country = rng.choice(COMPANIES)
        role = rng.choice(ROLES)
        level = _pick(rng, SENIORITY)
        title = f"{level}{role}"
        years = {"Junior ": "0-2", "": "2-4", "Senior ": "5+", "Staff ": "8+"}[level]
        skills = rng.sample(SKILL_LINES, k=rng.randint(3, 6))
        language = _pick(rng, LANGUAGE_LINES)
        visa = _pick(rng, VISA_LINES)
        workplace = _pick(rng, WORKPLACE_LINES)
        team = rng.choice(["platform", "data", "AI", "product"])
        description = "\n\n".join(
            part
            for part in [
                f"{company} is hiring a {title} to join our {team} team in {location}.",
                "What you will work with:\n" + "\n".join(f"- {s}" for s in skills),
                f"Experience: {years} years in a similar role.",
                language,
                visa,
                workplace,
                "This posting is synthetic demo data generated by eu-job-pipeline. The company does not exist.",
            ]
            if part
        )
        source = rng.choice(SOURCES)
        jobs.append(
            Job(
                source=source,
                external_id=f"demo-{n:04d}",
                title=title,
                company=company,
                location=location,
                country=country,
                remote="remote" in workplace.lower(),
                url=f"https://example.com/jobs/{source}/demo-{n:04d}",
                description=description,
                posted_at=(today - timedelta(days=rng.randint(0, 45))).date(),
                tags=[role.split(" (")[0], level.strip() or "Mid"],
            )
        )
    return jobs


_HOST_TO_FIXTURE = {
    "www.arbeitnow.com": "arbeitnow.json",
    "rest.arbeitsagentur.de": "bundesagentur.json",
    "boards-api.greenhouse.io": "greenhouse.json",
    "api.lever.co": "lever.json",
}


def fixture_transport(fixtures_dir: Path) -> httpx.MockTransport:
    """Serves recorded API responses so `fetch` works offline in demo mode and in tests."""

    def handler(request: httpx.Request) -> httpx.Response:
        name = _HOST_TO_FIXTURE.get(request.url.host)
        if not name:
            return httpx.Response(404, json={"error": f"no fixture for {request.url.host}"})
        path = Path(fixtures_dir) / "sources" / name
        if not path.exists():
            return httpx.Response(404, json={"error": f"missing fixture {path.name}"})
        return httpx.Response(
            200, content=path.read_bytes(), headers={"content-type": "application/json"}
        )

    return httpx.MockTransport(handler)


def write_fixture(path: Path, payload: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
